name: Deploy on Push to Main

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # or whichever version you need

      - name: Install dependencies
        run: npm install

      # (Optional) Run tests
      - name: Run tests
        run: npm test

      # Build your Lambda functions (if you have a build step)
      - name: Build Lambda
        run: |
          npm run build-lambda
          # e.g., output your zipped Lambda to ./lambda_functions.zip

      # If you prefer manually zipping:
      - name: Zip Lambda files
        run: |
          cd src/handlers
          zip -r ../../lambda_functions.zip ./*
          cd ../../

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change to your region

      # --- Serverless Deployment ---
      - name: Install Serverless
        run: npm install -g serverless

      - name: Deploy with Serverless
        run: serverless deploy

      # --- Terraform Deployment ---
      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve